escapadas_a_tu_medida/alquileres/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('reservar/<int:propiedad_id>/', views.crear_reserva, name='crear_reserva'),
    path('crear_reserva_ya_pagada/<int:propiedad_id>/', views.crear_reserva_ya_pagada, name='crear_reserva_ya_pagada'),
    path('confirmar_reserva/<int:propiedad_id>/', views.confirmar_reserva, name='confirmar_reserva'),
    path('pagoRealizado/', views.pago_realizado, name='pago_realizado'),
    path('buscar/', views.buscar_alojamientos, name='buscar_alojamientos'),
    path('gestionPropiedad/create', views.crear_propiedad, name='crear_propiedad'),
    path('gestionPropiedad/delete/<int:propiedad_id>/', views.eliminar_propiedad, name='eliminar_propiedad'),
    path('gestionPropiedad/update/<int:propiedad_id>/', views.actualizar_propiedad, name='editar_propiedad'),
    path('gestionPropiedad/show/<int:propiedad_id>/', views.mostrar_detalles_propiedad, name='mostrar_propiedad'),
    path('gestionPropiedad/', views.listar_propiedades_propietario, name='listar_propiedades_propietario'),
    path('historialReservas/', views.historial_reservas, name='historial_reservas'),
    path('seguimientoReservas/<int:reserva_id>/', views.seguir_reservas, name='seguir_reservas'),
    path('agregarListaDeseos/<int:propiedad_id>/', views.agregar_propiedad_deseada, name='agregar_lista_deseos'),
    path('listaDeseos/', views.obtener_lista_deseos, name='lista_deseos'),
    path('eliminarListaDeseos/<int:propiedad_id>/', views.eliminar_de_lista_deseos, name='eliminar_lista_deseos'),
    path('valorarPropiedad/<int:propiedad_id>/', views.valorar_propiedad, name='valorar_propiedad'),
]

escapadas_a_tu_medida/escapadas_a_tu_medida/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alquileres.urls')),
    path('', include('usuarios.urls')),
    path('', include('pago.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

escapadas_a_tu_medida/pago/urls.py
from django.urls import path
from . import views

from django.conf import settings

urlpatterns = [
    path('pago/<int:propiedad_id>/<str:monto>/', views.procesar_pago, name='procesar_pago'),

]

escapadas_a_tu_medida/alquileres/models.py
# alquileres/models.py

import datetime
from django.db import models
from django.forms import ValidationError
from usuarios.models import PerfilUsuario
from django.utils.timezone import now

# models.py
from django.db import models

class Propiedad(models.Model):

    TIPO_PROPIEDAD_CHOICES = [
        ('apartamento', 'Apartamento'),
        ('casa', 'Casa'),
        ('habitacion', 'Habitación'),
        ('villa', 'Villa'),
        ('estudio', 'Estudio'),
        ('loft', 'Loft'),
        ('bungalow', 'Bungalow'),
        ('cabaña', 'Cabaña'),
        ('castillo', 'Castillo'),
        ('caravana', 'Caravana'),
        ('barco', 'Barco'),
        ('iglú', 'Iglú'),
        ('finca', 'Finca'),
        ('chalet', 'Chalet'),
        ('casa_rural', 'Casa Rural'),
        ('residencia_universitaria', 'Residencia Universitaria'),
        ('penthouse', 'Penthouse'),
        ('granja', 'Granja'),
        ('hostal', 'Hostal'),
        ('hotel', 'Hotel'),
        ('camping', 'Camping'),
        ('resort', 'Resort'),
        ('tienda_de_campaña', 'Tienda de Campaña'),
        ('casa_flotante', 'Casa Flotante'),
        ('casa_en_arbol', 'Casa en Árbol'),
        ('domo', 'Domo'),
        ('yurta', 'Yurta'),
        ('container', 'Container'),
        ('apartamento_estudio', 'Apartamento Estudio'),
        ('aparthotel', 'Aparthotel'),
    ]
        
    propietario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE, limit_choices_to={'tipo_usuario': 'anfitrion'})
    titulo = models.CharField(max_length=255)
    descripcion = models.TextField()
    ubicacion = models.CharField(max_length=255)
    precio_por_noche = models.DecimalField(max_digits=10, decimal_places=2)
    num_maximo_huespedes = models.IntegerField()
    num_maximo_habitaciones = models.IntegerField()
    servicios_disponibles = models.TextField()
    tipo = models.CharField(max_length=50, choices=TIPO_PROPIEDAD_CHOICES)  # Campo con opciones predefinidas


    def __str__(self):
        return self.titulo
    
    def obtener_promedio_calificacion(self):
        valoraciones = self.valoraciones.all()
        if not valoraciones.exists():
            return None  # O puedes devolver 0, dependiendo de cómo quieras manejarlo
        return valoraciones.aggregate(models.Avg('calificacion'))['calificacion__avg']

    def clean(self):
        super().clean()

        if self.precio_por_noche <= 0:
            raise ValidationError("El valor debe ser positivo")


    
        if self.pk and not self.imagenes.exists():
            raise ValidationError("Cada propiedad debe tener al menos una imagen asociada.")

        # Validación de fechas en disponibilidades
        if self.pk:
            fechas_invalidas = self.disponibilidades.filter(fecha__lt=now().date())
            if fechas_invalidas.exists():
                raise ValidationError("La propiedad tiene fechas de disponibilidad anteriores a la actual.")
    
class Disponibilidad(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name='disponibilidades')
    fecha = models.DateField()

    class Meta:
        unique_together = ('propiedad', 'fecha')  # Asegura que no haya duplicados

    def __str__(self):
        return f"{self.propiedad.titulo} - {self.fecha}"
    
    def clean(self):
        super().clean()
        
        # Validación: La fecha no debe ser anterior a la actual
        if self.fecha < now().date():
            raise ValidationError("La fecha de disponibilidad no puede ser anterior a la fecha actual.")

    

class Imagen(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name='imagenes')  # Relación de muchas a uno con Propiedad
    imagen = models.ImageField(upload_to='propiedades/', blank=True)  # Campo para la imagen
    
    def __str__(self):
        return f"Imagen de {self.propiedad.titulo}"




class Reserva(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    inquilino = models.ForeignKey(
        PerfilUsuario, 
        on_delete=models.CASCADE, 
        null=True, 
        blank=True, 
        limit_choices_to={'tipo_usuario': 'inquilino'}
    )
    nombre_usuario_anonimo = models.CharField(max_length=255, null=True, blank=True)
    correo_usuario_anonimo = models.EmailField(null=True, blank=True)
    telefono_usuario_anonimo = models.CharField(max_length=20, null=True, blank=True)
    numero_huespedes = models.IntegerField()
    fechas_reserva = models.JSONField(default=list)  # Almacena las fechas reservadas como una lista
    total = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.fechas_reserva:
            raise ValidationError("Debe seleccionar al menos una fecha para la reserva.")

        fechas_seleccionadas = set(self.fechas_reserva)
        disponibilidades = Disponibilidad.objects.filter(
            propiedad=self.propiedad,
            fecha__in=fechas_seleccionadas
        )

        if disponibilidades.count() != len(fechas_seleccionadas):
            raise ValidationError("Una o más fechas seleccionadas no están disponibles.")

        disponibilidades.delete()

        if not self.total:
            self.total = len(fechas_seleccionadas) * self.propiedad.precio_por_noche

        super().save(*args, **kwargs)

    def __str__(self):
        fechas = ", ".join(self.fechas_reserva)
        if self.inquilino:
            return f"Reserva de {self.inquilino} para {self.propiedad} en las fechas: {fechas}"
        return f"Reserva de {self.nombre_usuario_anonimo} ({self.correo_usuario_anonimo}) para {self.propiedad} en las fechas: {fechas}"



class PropiedadesDeseadas(models.Model):
    inquilino = models.ManyToManyField(PerfilUsuario, related_name='propiedades_deseadas')
    propiedad = models.ManyToManyField(Propiedad, related_name='propiedades_deseadas')


    def str(self):
        return f"{', '.join([str(p) for p in self.propiedad.all()])} - {', '.join([i.usuario.nombre for i in self.inquilino.all()])}"

class Valoracion(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE, related_name='valoraciones')
    usuario = models.ForeignKey(PerfilUsuario, on_delete=models.CASCADE, related_name='valoraciones')
    calificacion = models.PositiveSmallIntegerField()  # Por ejemplo, de 1 a 5

    class Meta:
        unique_together = ('propiedad', 'usuario')  # Un usuario solo puede valorar una propiedad una vez

    def __str__(self):
        return f"{self.usuario} valoró {self.propiedad} con {self.calificacion} estrellas"

    def clean(self):
        super().clean()
        if self.calificacion < 1 or self.calificacion > 5:
            raise ValidationError("La calificación debe estar entre 1 y 5.")

escapadas_a_tu_medida/alquileres/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Propiedad, Imagen, Reserva

class ImagenForm(forms.ModelForm):
    class Meta:
        model = Imagen
        fields = ['imagen']


# Crear un formset para las imágenes asociadas a una propiedad
ImagenFormSet = inlineformset_factory(
    Propiedad, Imagen,  # Relación entre propiedad e imagen
    form=ImagenForm,  # Formulario para cada imagen
    extra=10,  # Añade un formulario vacío inicialmente
    max_num=10,  # Límite de 10 imágenes
    can_delete=False  # Opción para eliminar imágenes
)

class PropiedadForm(forms.ModelForm):
    class Meta:
        model = Propiedad
        fields = ['titulo', 'descripcion', 'ubicacion', 'precio_por_noche', 'num_maximo_huespedes', 'num_maximo_habitaciones', 'servicios_disponibles', 'tipo']

class FiltroAlojamientosForm(forms.Form):
    query = forms.CharField()
    ubicacion = forms.CharField(required=False, label="Ubicación")
    precio_min = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Precio mínimo")
    precio_max = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Precio máximo")
    num_maximo_huespedes = forms.IntegerField(required=False, label="Número de huéspedes")
    num_maximo_habitaciones = forms.IntegerField(required=False, label="Número de habitaciones")
    tipo = forms.CharField(required=False, label="Tipo")
    valoracion_minima = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Valoración mínima")

class FiltroAlojamientosHomeForm(forms.Form):
    ubicacion = forms.CharField(required=False, label="Ubicación")
    precio_min = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Precio mínimo")
    precio_max = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Precio máximo")
    num_maximo_huespedes = forms.IntegerField(required=False, label="Número de huéspedes")
    num_maximo_habitaciones = forms.IntegerField(required=False, label="Número de habitaciones")
    tipo = forms.CharField(required=False, label="Tipo")
    valoracion_minima = forms.DecimalField(max_digits=10, decimal_places=2, required=False, label="Valoración mínima")


class ReservaForm(forms.ModelForm):
    numero_huespedes = forms.IntegerField(initial=1)
    class Meta:
        model = Reserva

        fields = ['numero_huespedes', 'nombre_usuario_anonimo', 'correo_usuario_anonimo', 'telefono_usuario_anonimo']


    def __init__(self, *args, **kwargs):
        self.propiedad_id = kwargs.pop('propiedad_id', None)  # Extrae el id de la propiedad
        self.user_authenticated = kwargs.pop('user_authenticated', False)
        super().__init__(*args, **kwargs)

        if not self.user_authenticated:
            self.fields['nombre_usuario_anonimo'].required = True
            self.fields['correo_usuario_anonimo'].required = True
            self.fields['telefono_usuario_anonimo'].required = True
        else:
            # Si el usuario está autenticado, no hacer estos campos obligatorios
            self.fields['nombre_usuario_anonimo'].required = False
            self.fields['correo_usuario_anonimo'].required = False
            self.fields['telefono_usuario_anonimo'].required = False

    def clean_numero_huespedes(self):
        n_huespedes = self.cleaned_data.get('numero_huespedes',0)
        
        # Asegúrate de que la propiedad existe
        try:
            propiedad = Propiedad.objects.get(id=self.propiedad_id)
        except Propiedad.DoesNotExist:
            raise forms.ValidationError("La propiedad no existe.")

        # Verifica si el número de huéspedes excede el máximo permitido
        if propiedad.num_maximo_huespedes < n_huespedes:
            raise forms.ValidationError("El número de huéspedes no puede ser mayor al permitido.")

        return n_huespedes
    



        

escapadas_a_tu_medida/alquileres/templates/alquileres/confirmar_reserva.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reserva Confirmada</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- FontAwesome for Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f7f9fc;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .card {
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }

        .card-title {
            font-size: 1.8rem;
            font-weight: 600;
            color: #2c3e50;
        }

        .card-text {
            font-size: 1rem;
            color: #7f8c8d;
            margin-bottom: 20px;
        }

        .btn-primary {
            background-color: #304a6e;
            border: none;
        }

        .btn-primary:hover {
            background-color: #203040;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card text-center p-4">
                    <div class="card-body">
                        <i class="fas fa-check-circle fa-3x text-success mb-3"></i>
                        <h2 class="card-title">¡Reserva Confirmada!</h2>
                        <p class="card-text">Tu reserva ha sido confirmada y el pago se ha realizado con éxito.</p>
                        <p class="card-text">Te hemos enviado un correo con los detalles de la reserva.</p>
                        <a href="/" class="btn btn-primary">
                            <i class="fas fa-home me-2"></i>Volver a la página principal
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

escapadas_a_tu_medida/alquileres/templates/alquileres/correo_reserva.html
<!DOCTYPE html>
<html>
<head>
    <title>Reserva confirmada</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        h1 {
            color: #2c3e50;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        .info {
            margin-top: 20px;
        }
        .info p {
            margin: 5px 0;
        }
        .footer {
            margin-top: 20px;
            font-size: 0.9em;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>¡Hola, {{ usuario}}!</h1>
        <p>Gracias por tu reserva en <strong>{{ reserva.propiedad.titulo }}</strong>. Aquí están los detalles:</p>

        <div class="info">
            <p><strong>Ubicación:</strong> {{ reserva.propiedad.ubicacion }}</p>
            <p><strong>Descripción:</strong> {{ reserva.propiedad.descripcion }}</p>
            <p><strong>Fechas reservadas:</strong> 
                {% for fecha in reserva.fechas_reserva %}
                    {{ fecha }}{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p><strong>Número de huéspedes:</strong> {{ reserva.numero_huespedes }}</p>
            <p><strong>Total a pagar:</strong> {{ reserva.total }} €</p>
        </div>

        <p>Para hacer el seguimiento de tu reserva, haz clic en el siguiente enlace:</p>
        <p><a href="{{url_seguimiento}}">Seguir mi reserva</a></p>
    

        <p>Estamos emocionados de recibirte pronto. Si tienes alguna pregunta, no dudes en contactarnos.</p>

        <div class="footer">
            <p>Equipo de Escapadas a tu Medida</p>
        </div>
    </div>
</body>
</html>

escapadas_a_tu_medida/alquileres/templates/alquileres/crear_reserva.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Nueva Reserva</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- FontAwesome Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <style>
        /* Establece la altura de la página completa */
        body,
        html {
            height: 100%;
            /* Asegura que el body y html ocupen el 100% de la altura */
            margin: 0;
            /* Elimina los márgenes predeterminados */
        }

        /* Centrar el contenido de la página */
        .container-fluid {
            height: 100vh;
            /* Hace que el contenedor ocupe toda la altura de la ventana */
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 0 20px;
            /* Espaciado lateral */

        }

        .crear-reserva-container {
            background-color: #fff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 1000px;
            /* Aumenta el ancho máximo */
            position: relative;
            display: flex;
            flex-direction: column;
            justify-content: center;

        }

        h2,
        h3 {
            font-weight: 700;
            color: #333;
            text-align: center;
            margin-bottom: 20px;
        }

        h2 {
            margin-top: 0;
            /* Elimina margen superior del título */

        }

        h3 {
            font-size: 1.25rem;
            margin-bottom: 15px;
        }

        label {
            font-size: 16px;
            font-weight: 600;
            color: #333;
            display: block;
            /* Cambia a block para que el texto esté encima del campo */
            margin-bottom: 8px;
            /* Espaciado entre la etiqueta y el campo */
            text-align: left;
            /* Alinea a la izquierda */
        }

        .form-group {
            margin-bottom: 25px;
            /* Aumenta el margen entre los campos */
            display: flex;
            flex-direction: column;

        }

        .form-control {
            width: 100%;
            height: 45px;
            /* Aumenta la altura de los campos de entrada */
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;

            font-size: 16px;
            transition: height 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease;
            font-family: 'Roboto', sans-serif;
        }

        .form-control:focus {
            box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
            border-color: #007bff;
        }


        textarea {
            resize: none;
            overflow: hidden;
        }

        button[type="submit"] {
            margin-top: 20px;
            font-weight: 500;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 12px 20px;
            transition: background-color 0.3s ease;
            font-size: 18px;
            /* Aumenta el tamaño del texto */

        }

        button[type="submit"]:hover {
            background-color: #2a3f5b;
            color: #fff;
            /* Azul más oscuro al pasar el mouse */
        }

        input:focus,
        textarea:focus,
        select:focus {
            outline: none;
            border-color: #304a6e;
            box-shadow: 0 0 4px rgba(48, 74, 110, 0.4);
        }

        .alert-info {
            background-color: #e6eef7;
            color: #304a6e;
        }

        .close-btn {
            position: absolute;
            top: 20px;
            left: 20px;
            font-size: 24px;
            background-color: transparent;
            border: none;
            cursor: pointer;
        }

        .close-btn i {
            color: black;
        }

        .form-group input,
        .form-group textarea {
            width: 100%;
            height: 45px;
        }

        /* Para hacer que los inputs de tipo texto sean más altos */
        .form-group .form-control {
            font-size: 16px;
        }

        /* Asegura que el formulario sea responsive */
        .form-group input,
        .form-group textarea {
            width: 100%;
        }

        /* Botón con un tamaño adecuado */
        .btn-primary {
            width: 100%;
            padding: 12px 20px;
            font-size: 18px;
            font-weight: 600;
        }

        .custom-h3 {
            font-size: 16px;
            /* Cambia el tamaño de la fuente */
            font-weight: 600;
            /* Modifica el peso de la fuente */
            margin-bottom: 10px;
            /* Ajusta el espacio debajo del h3 */
            text-align: left;

        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
</head>

<body>
    <div class="container-fluid">
        <div class="crear-reserva-container">
            <!-- Botón para cerrar con el ícono de casa a la izquierda -->
            <button class="close-btn" onclick="window.location.href='/'">
                <i class="fas fa-home"></i>
            </button>

            <h2 class="mb-4">Crear Nueva Reserva</h2>
            <form method="POST">
                {% csrf_token %}

                <!-- Detalles de la Propiedad -->

                {% if not user_authenticated %}
                <div class="form-group">
                    <label for="id_nombre">Nombre:</label>
                    {{ reserva_form.nombre_usuario_anonimo }}
                    {% if reserva_form.nombre_usuario_anonimo.errors %}
                    <div class="text-danger">
                        {% for error in reserva_form.nombre_usuario_anonimo.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="id_correo">Correo electrónico:</label>
                    {{ reserva_form.correo_usuario_anonimo }}
                    {% if reserva_form.correo_usuario_anonimo.errors %}
                    <div class="text-danger">
                        {% for error in reserva_form.correo_usuario_anonimo.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <label for="id_numero_huespedes">Número de teléfono:</label>
                    {{ reserva_form.telefono_usuario_anonimo }}
                    {% if reserva_form.telefono_usuario_anonimo.errors %}
                    <div class="text-danger">
                        {% for error in reserva_form.telefono_usuario_anonimo.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                {% endif %}



                <div class="form-group">
                    <label for="{{ reserva_form.numero_huespedes.id_for_label }}">Número de huéspedes:</label>
                    {{ reserva_form.numero_huespedes }} <!-- Muestra el campo -->

                    <!-- Muestra los errores solo si el campo tiene errores -->
                    {% if reserva_form.numero_huespedes.errors %}
                    <div class="text-danger">
                        <!-- Mostrar cada error debajo del campo -->
                        {% for error in reserva_form.numero_huespedes.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-group">
                    <h3 class="custom-h3">Seleccionar Fechas:</h3>
                    <input type="text" id="fechas_escogidas" name="fechas_escogidas" placeholder="Selecciona las fechas" class="form-control" required  />


                </div>

                <button type="submit" class="btn btn-primary">Crear Reserva</button>

            </form>


        </div>

        {% if request.method == "POST" %}
        {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field in form %}
                {% if field.errors %}
                <li>{{ field.label }}: {{ field.errors }}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endif %}


    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Flatpickr JS -->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const fechasDisponiblesExistentes = "{{ fechas_disponibles }}".split(",").map(f => f.trim()); // Elimina espacios en blanco        

            flatpickr("#fechas_escogidas", {
                mode: "multiple", // Permitir seleccionar varias fechas
                dateFormat: "Y-m-d", // Formato de fecha (año-mes-día)
                enable: fechasDisponiblesExistentes,
                

            });
        });


        document.querySelector("form").addEventListener("submit", function(event) {
            const fechas = document.getElementById("fechas_escogidas").value.trim();

            if (!fechas) {
                event.preventDefault(); // Detiene el envío del formulario
                alert("Por favor selecciona al menos una fecha.");
            }
        });

    </script>
</body>

</html>

escapadas_a_tu_medida/alquileres/templates/alquileres/historial_reservas.html
{% extends "base.html" %}

{% block title %}Historial de reservas{% endblock %}

{% block content %}
{% block navbar_custom_styles %}
<style>
    .navbar {
        height: 250px;
        /* Cambiar la altura solo en esta página */
    }
</style>
{% endblock %}
{% block search_bar %} {% endblock %}


<div class="container my-4">
    {% if reservas %}
    <div class="row row-cols-1 g-4">
        {% for reserva in reservas %}
        <div class="col">
            <div class="card mb-4" style="display: flex; flex-direction: row; align-items: center; padding: 1rem;">  
                <!-- Información de la propiedad -->
                <div class="card-body">
                    <h4 class="card-title">{{ reserva.propiedad.titulo }}</h4>
                    <p class="card-text text-muted" style="font-size: 0.85rem;">
                        <i class="fas fa-map-marker-alt me-2"></i>{{ reserva.propiedad.ubicacion }}
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No hay reservas disponibles.</p>
    {% endif %}
</div>

{% endblock %}